on:
  release:
    types: [created]

name: Build

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-build
      - name: "Build msi installer"
        run: ./gradlew.bat packageReleaseMsi

      - run: |
          mkdir release-files
          mv composeApp/build/compose/binaries/main-release/msi/*.msi release-files/spellbook-installer-${{ github.event.release.tag_name }}.msi
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} release-files/*.msi

      - uses: actions/upload-artifact@v7
        with:
          name: windows release build
          path: release-files/*.msi

  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-build

      - uses: mobiledevops/secret-to-file-action@v2
        with:
          base64-encoded-secret: ${{ secrets.SECRET_KEYSTORE }}
          filename: "secrets/keystore.jks"

      - env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SECRET_STORE_PASSWORD }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SECRET_KEY_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ vars.SIGNING_KEY_ALIAS }}
        name: "Build releases"
        run: ./gradlew --info createReleaseDistributable packageReleaseDeb packageReleaseApk packageReleaseUberJarForCurrentOS

      - run: |
          mkdir release-files
          mv composeApp/build/outputs/apk_from_bundle/release/*.apk release-files/spellbook-${{ github.event.release.tag_name }}.apk
          mv composeApp/build/compose/binaries/main-release/deb/org.fufu.spellbook_*.deb release-files/spellbook-${{ github.event.release.tag_name }}.deb
          mv composeApp/build/compose/jars/org.fufu.spellbook-linux-x64-*-release.jar release-files/spellbook-${{ github.event.release.tag_name }}.jar
          tar -czvf release-files/spellbook-${{ github.event.release.tag_name }}.tar.gz composeApp/build/compose/binaries/main-release/app

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} release-files/*

      - uses: actions/upload-artifact@v7
        with:
          name: release builds
          path: release-files/*