on:
  release:
    types: [created]

name: Build

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: $/actions/setup-build
      - name: "Build msi installer"
        run: ./gradlew.bat packageReleaseMsi

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} composeApp/build/binaries/main-release/msi/*.msi

      - uses: actions/upload-artifact@v4
        with:
          name: windows release build
          path: composeApp/build/binaries/main-release/msi/*.msi

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: $/actions/setup-build
      - name: "Build releases"
        run: ./gradlew createReleaseDistributable packageReleaseDeb packageReleaseApk packageReleaseUberJarForCurrentOS

      - run: |
          mkdir release-files
          mv composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk release-files/spellbook-${{ github.event.release.tag_name }}.apk
          mv composeApp/build/compose/binaries/main-release/deb/org.fufu.spellbook_*.deb release-files/spellbook-${{ github.event.release.tag_name }}.deb
          mv composeApp/build/compose/jars/org.fufu.spellbook-linux-x64-*-release.jar release-files/spellbook-${{ github.event.release.tag_name }}.jar
          tar -czvf release-files/spellbook-${{ github.event.release.tag_name }}.tar.gz composeApp/build/compose/binaries/main-release/app

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} release-files/*

      - uses: actions/upload-artifact@v4
        with:
          name: release builds
          path: release-files/*